steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn install -Ptest -Dusername=apigee-deploy@example.com -Dpassword=$$PASSWORD']
  dir: 'HelloWorld'
  secretEnv: ['PASSWORD']


secrets:
- kmsKeyName: projects/scenic-medium-239918/locations/global/keyRings/Bhagya_Reddy/cryptoKeys/Bhagya
  secretEnv:
    PASSWORD:=OoQ:l~%"Ksj?P"@)vF9&
